### ISSUE TITLE
EnergyShaders [Java] Armor rendering is broken

### ISSUE THREAD

**Issue by Lolothepro** [lni-dev/MinecraftShaders#1]
![2023-12-23_17 59 17](https://github.com/lni-dev/MinecraftShaders/assets/68275908/1ea82d12-e780-40c2-9aca-b21e15f32b48)

**Comment by lni-dev** [comment]
Are you on vanilla or Sodium?
Is your armor enchanted?

**Comment by Lolothepro** [comment]
Vanilla, and no

**Comment by lni-dev** [comment]
Is fixed now. A new update containing the fix will be available when Minecraft 1.20.5 is released.

**Comment by lni-dev** [comment]
:)
